name: heavy_assistant
description: "assistant application for heavy equipment driver"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.11.0
  flutter_naver_map: ^1.2.3+1
  geolocator: ^8.2.1
  permission_handler: ^10.0.0
  fluttertoast: ^8.2.5
  shared_preferences: ^2.0.15
  logger: ^1.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  geolocator_android: 4.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
